# This is a basic workflow to help you get started with Actions

name: Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'main'
    tags:
      - '*' # 任何标签都触发

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - qt_ver: 6.7.2
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64  
    env:
      fileName: CommHelper_${{ github.ref_name }}.exe
      fileNameNoSuffix: CommHelper_${{ github.ref_name }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
#          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          ref: main
          submodules: recursive
          
      - name: Install Dependencies
        run: |
          choco install --no-progress sccache ninja -y
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          target: 'desktop'
          arch: ${{ matrix.qt_arch }}
          use-official: true
          cache: true
          modules: qtcharts qtlocation qtpositioning qt5compat qtmultimedia qtserialport qtremoteobjects qtshadertools
     
      - name: Cache sccache compilation results
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\AppData\Local\sccache
          key: ${{ runner.os }}-sccache-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-sccache-
          
      - name: msvc-build
        id: build
        shell: cmd
        run: |
          sccache --show-stats
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          ninja --version
          if not exist build mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH=D:\a\CommHelper\Qt\${{ matrix.qt_ver }}\msvc2019_64 ^
                -DCMAKE_C_COMPILER_LAUNCHER=sccache ^
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache ^
                -DCMAKE_C_COMPILER=cl ^
                -DCMAKE_CXX_COMPILER=cl ^
                -DCMAKE_BUILD_TYPE=Release ^
                -GNinja -S .. -B .
          cmake --build . --target all --config Release --parallel
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%
          
      - name: inno setup install
        # 只有以tag触发的操作,才会执行打包,取消后，不管是push还是tag都会执行打包
#        if: startsWith(github.event.ref, 'refs/tags/')
        uses: zhuzichu520/inno-setup-action@v1.0.1
        with:
          filepath: ./workflows/action-cli/InstallerScript.iss
          
      - name: uploadRelease
        # 只有以tag触发的操作,才会执行release 操作,上传到release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: ./workflows/action-cli/installer.exe
          asset_name: ${{ env.fileNameNoSuffix }}_${{ matrix.msvc_arch }}_windows.exe
          tag: ${{ github.ref }}
          overwrite: true 

      - name: Save main artifact
        uses: actions/upload-artifact@master
        # 只有当master更新时才会触发，tag操作不触发,
        if: startsWith(github.event.ref, 'refs/heads/') && startsWith(github.ref, 'refs/heads/')
        with:
          name: main
          path: ./workflows/action-cli/installer.exe
          retention-days: 1 # 保留1天，因为只有500M的保存空间，每个工件50M
          compression-level: 0 # 因为上传的是二进行文件，不使用压缩
          overwrite: true

      - name: Rename the file using CMD
        # 提交tag触发的操作中... 更改名字，生成以版本号的命名和exe文件
        if: startsWith(github.event.ref, 'refs/tags/')
        run: rename ".\workflows\action-cli\installer.exe" ${{ env.fileNameNoSuffix }}_${{ matrix.msvc_arch }}_windows.exe
        shell: cmd

 

